# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:57
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_auto_20180315_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='searcher_qu_search__705394_gin'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='searcher_co_search__bdd341_gin'),
        ),
    ]
