# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 09:13
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motion',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='motion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='searcher_mo_search__5259da_gin'),
        ),
    ]
